# Generated by Django 4.1.4 on 2023-01-30 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('cnpj', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('nome_fantasia', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=9)),
                ('numero', models.IntegerField()),
                ('rua', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EspacoHabitacional',
            fields=[
                ('idEspacoHabitacional', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=75)),
                ('descricao', models.CharField(max_length=500)),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='condominium.condominio', verbose_name='cnpj')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=75)),
                ('telefone', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=250)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEspacoHabitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('espaco_habitacional', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='condominium.espacohabitacional')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='condominium.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('idImovel', models.AutoField(primary_key=True, serialize=False)),
                ('informacao_complementar', models.CharField(max_length=500)),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='condominium.condominio', verbose_name='cnpj')),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='condominium.pessoa', verbose_name='cpf')),
            ],
        ),
        migrations.AddField(
            model_name='espacohabitacional',
            name='reserva',
            field=models.ManyToManyField(related_name='pessoas', through='condominium.ReservaEspacoHabitacional', to='condominium.pessoa'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='cpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='condominium.pessoa', verbose_name='cpf'),
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('idAviso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=75)),
                ('descricao', models.CharField(max_length=500)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='condominium.condominio', verbose_name='cnpj')),
            ],
        ),
    ]
