# Generated by Django 4.1.4 on 2023-01-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('senha', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
