# Generated by Django 4.1.4 on 2023-01-05 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.pessoa')),
                ('condominio_id', models.IntegerField()),
                ('imovel_id', models.IntegerField()),
            ],
            bases=('users.pessoa',),
        ),
        migrations.CreateModel(
            name='Sindico',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.pessoa')),
                ('condominio_id', models.IntegerField()),
            ],
            bases=('users.pessoa',),
        ),
    ]
