# Generated by Django 4.1.4 on 2023-01-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_morador_sindico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('aviso_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_envio', models.DateField()),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField(max_length=300)),
                ('anexo', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('cnpj', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=101)),
            ],
        ),
        migrations.CreateModel(
            name='EspacoHabitacional',
            fields=[
                ('espaco_habitacional_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=101)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('imovel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('qtd_morador', models.IntegerField()),
                ('bloco', models.CharField(max_length=101)),
                ('numero', models.IntegerField()),
                ('nome', models.CharField(max_length=101)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
