# Generated by Django 4.1.4 on 2023-01-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_aviso_condominio_espacohabitacional_imovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='anexo',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='data_envio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='descricao',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='titulo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='nome',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='espacohabitacional',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='espacohabitacional',
            name='nome',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='bloco',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='nome',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='qtd_morador',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='morador',
            name='condominio_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='morador',
            name='imovel_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sindico',
            name='condominio_id',
            field=models.IntegerField(null=True),
        ),
    ]
