# Generated by Django 4.1.4 on 2023-01-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_aviso_anexo_alter_aviso_data_envio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('boleto_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pagou', models.BooleanField(null=True)),
                ('nome', models.CharField(max_length=101, null=True)),
                ('valor', models.IntegerField(null=True)),
                ('data_ref', models.DateField(null=True)),
                ('origem', models.CharField(max_length=101, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('custo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField(null=True)),
                ('nome', models.CharField(max_length=101, null=True)),
                ('descricao', models.TextField(null=True)),
                ('data_ref', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('endereco_id', models.IntegerField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=101, null=True)),
                ('cep', models.IntegerField(null=True)),
                ('cidade', models.CharField(max_length=101, null=True)),
                ('estado', models.CharField(max_length=2, null=True)),
                ('pais', models.CharField(max_length=101, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reserva_id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=101, null=True)),
                ('data_inicio', models.DateTimeField(null=True)),
                ('data_fim', models.DateTimeField(null=True)),
            ],
        ),
    ]
